# Generated by Django 4.0.4 on 2022-05-19 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0002_alter_menu_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menu', 'verbose_name_plural': 'Menu'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Order item', 'verbose_name_plural': 'Order items'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': 'Table', 'verbose_name_plural': 'Tables'},
        ),
        migrations.RemoveField(
            model_name='menu',
            name='item',
        ),
    ]
